### ISSUE TITLE
Generic type arguments in JSX elements

### ISSUE THREAD

**Issue by detrohutt** [strothj/react-app-rewire-typescript-babel-preset#16]
I'm trying to use the feature described in [the release notes for ts 2.9](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html) under the heading "Generic type arguments in JSX elements".

Whenever I use this feature, neither `tsc` nor my editor (VS Code 1.25.1) shows any errors. However, when I run `yarn start` CRA throws an error that simply says `Failed to compile.` and the path to the file where I used the new syntax.

Have you been able to successfully use this feature? I'm not entirely sure it has anything to do with your project.

##### Package versions
- typescript@^2.9.2
- react-app-rewire-typescript-babel-preset@^2.3.0
- react-scripts@2.0.0-next.3e165448
- @babel/preset-typescript@^7.0.0-beta.55

**Comment by strothj** [comment]
You'll need to pin the version of @babel-parser using the `resolutions` field in package.json. I know Yarn supports it, not sure about NPM.  That's until hopefully CRA releases another beta with an updated parser.

The parser has additions for the new nodes for that feature.

```
"resolutions": {
  "@babel/parser": "^7.0.0-beta.55",
}
```

**Comment by strothj** [comment]
Might also have to do `@babel/core`.

**Comment by detrohutt** [comment]
Awesome, that got CRA to compile! (I did also have to do `@babel/core`) Unfortunately it caused another typescript error with a package on my server, but I think I can get that sorted out. Thanks for your help and quick response! :)
