### ISSUE TITLE
Babel v7.0.0-beta.56 fails to compile

### ISSUE THREAD

**Issue by strothj** [strothj/react-app-rewire-typescript-babel-preset#17]
There was a breaking change in Babel:
https://github.com/babel/babel/pull/8266

Third party packages relying on Babel runtime may also run into issues (unrelated to this rewired):
https://github.com/mui-org/material-ui/issues/12408

Recommend pinning to Babel v7.0.0-beta.55 for the time being if you've forced resolutions to highest versions.

TODO:
- [ ] Remove depreciated option to Babel runtime preset `polyfill` when resolved runtime is v56 or above. `react-scripts` sets it to false explicitly which is now the default.

**Comment by papaponmx** [comment]
Here is the command to run.

`npm install --save-exact @babel/runtime@7.0.0-beta.55`

**Comment by strothj** [comment]
Closing this as Create React App has merged in Babel 7 proper (release still pending).

https://github.com/facebook/create-react-app/commit/0bdbe42768d0f5c2385365f34ac79e31aba2d6a6
