### ISSUE TITLE
Unable to configure Babel for Jest

### ISSUE THREAD

**Issue by lee-reinhardt** [strothj/react-app-rewire-typescript-babel-preset#18]
This rewire is working really great for me, thanks for maintaining it. The only issue I cannot solve is how to load additional Babel presets/plugins when running Jest.

When looking through the source, it looks like this is explicitly disabled -- in `rewireBabelTransform.js`:

```
const transformer = babelJest.createTransformer({
  presets: [path.resolve(__dirname, "rewirePreset")],
  babelrc: false
});
```

I see no way to override or change this behavior aside from patching the source in `node_modules`. I'm not the only person that's been tripped up by this: https://github.com/timarney/react-app-rewired/issues/250#issuecomment-393466807.

Would it be possible to change this option, or at least make it configurable in some way? Perhaps there's a good reason it's like this, but it was an unexpected limitation.

**Comment by strothj** [comment]
I believe I was referencing the original source from the react-scripts v2 package and that’s how it was there. I don’t know of any issues that would be caused by removing that.

I’m currently away from a computer. Do you know if react-app-rewired removes that normally?

**Comment by lee-reinhardt** [comment]
It is indeed disabled like this in CRA `react-scripts@next` [source here](https://github.com/facebook/create-react-app/blob/next/packages/react-scripts/config/jest/babelTransform.js#L16). This makes sense since they want little-to-no custom config.

However, in `react-app-rewired@next` this setting is flipped to `true`, [source here](https://github.com/timarney/react-app-rewired/blob/next/packages/react-app-rewired/scripts/utils/babelTransform.js#L16). (Changed in [this commit](https://github.com/timarney/react-app-rewired/commit/a85aba094824dd83aea76cfe257bcf301dca6820) a year ago)

If you're OK with this change, I can submit a PR to change it plus some docs that describe how to ensure your Babel plugins are loaded for Babel Jest.

**Comment by strothj** [comment]
Yes, that would be awesome thank you
