### ISSUE TITLE
Typings for svg files given on the installation docs throws an error

### ISSUE THREAD

**Issue by GabrielDuarteM** [strothj/react-app-rewire-typescript-babel-preset#23]
The current typings for SVG files given on the [installation docs](https://react-app-rewire-typescript-babel-preset.netlify.com/#/docs/installation?id=svg) are actually giving me a `[ts] Generic type 'SVGAttributes<T>' requires 1 type argument(s).` error on vscode.

This is probably because, using the latest typings, `React.SVGAttributes` expect a generic argument (probably `SVGSVGElement`, but not too sure about that).

There is an open PR on `create-react-app` to [add support to Typescript](https://github.com/facebook/create-react-app/pull/4837), and looking through the code, we can find their [typing file](https://github.com/facebook/create-react-app/blob/f33e0ca7f7fcb7474cb87ce0e73e74c6332a53e7/packages/react-scripts/template/index.d.ts), which includes `jpg` and `png` files as well. Maybe we could replace the current typings with those?

By the way, I'm using the following versions:

```
"@types/react": "^16.4.13",
"@types/react-dom": "^16.0.7"
```

**Comment by strothj** [comment]
Thanks for the call out. I had a goofy setting set in `tsconfig.json` which prevented this error from surfacing. I've updated the docs and examples to match.
