### ISSUE TITLE
Update Storybook examples for react-scripts@2.0.0

### ISSUE THREAD

**Issue by seniorquico** [strothj/react-app-rewire-typescript-babel-preset#26]
The Storybook example project configuration files don't appear to work with the latest react-script@2 betas. Comparing my working project configuration to the `webpack.config.js` example configuration file, I have the following:

- Remove @babel/preset-state-0 preset
- Add @babel/plugin-proposal-class-properties plugin
- Remove `polyfill: true` from @babel/plugin-transform-runtime plugin configuration

Additionally, I think the `webpack.config.monorepo.example.js` configuration file should be removed now that the latest react-scripts@2 betas no longer support Yarn workspaces/Lerna monorepos.

**Comment by strothj** [comment]
Hello,

I'm going to close this issue because the features of this project will soon be in the Create React App package. I've created an issue with some information here: https://github.com/strothj/react-app-rewire-typescript-babel-preset/issues/30
