### ISSUE TITLE
Monorepo and CRA 2

### ISSUE THREAD

**Issue by deftomat** [strothj/react-app-rewire-typescript-babel-preset#29]
I'm having issue with monorepo with a multiple TypeScript packages. 

Previously, I was able to import any TypeScript file from another package and compilation will handle it. However, after upgrading from `2.0.0-next.3e165448` to `2.0.4` typescript files from another packages or even from another directory than `src` are not compiled anymore.

Any suggestions why this happens?

**Comment by strothj** [comment]
Hello,

Unfortunately monorepo support was dropped between the beta and final release. I added some information about the situation here:
https://github.com/strothj/react-app-rewire-typescript-babel-preset/issues/30

It should be possible to reproduce that monorepo support by reviewing the the changes in the files listed in that linked issue. The CRA team also outlined some alternatives.

**Comment by deftomat** [comment]
Thank you for a detailed report in #30 👍 

I think that it is time to create my own build config as CRA brings more harm than good for us. We always need to rewire it anyway 😞 . 

I think that the biggest issue they have with a monorepo support is that they don't know which package should be transpiled or not. For TypeScript users, it's not a problem as we always need to transpile `*.ts` files.
