### ISSUE TITLE
setupTests file isn't rewired to typescript

### ISSUE THREAD

**Issue by barlock** [strothj/react-app-rewire-typescript-babel-preset#8]
If using a setupTests file for jest, the rewire doesn't update the jest config to point to a .ts extension.

**Comment by strothj** [comment]
Thanks for the report.

The earliest I’ll be able to look into this is Sunday. I would be willing to review a pull request if you want to put one together before then.

**Comment by strothj** [comment]
I think I have a working fix for this on the branch: feature/use-typescript-setup-tests-file

Will vet it more when I can.
